### ISSUE TITLE
CCE when applying transformers

### ISSUE THREAD

**Issue by RoccoDev** [MinecraftForge/CoreMods#19]
(Might be related to #16)

I am trying to apply a really simple transformer through JS.  
This is the JavaScript code:
```js
function initializeCoreMod() {
    print("Initializing Coremod");
    return {
        'loader': {
            'target': {
                'type': 'CLASS',
                'name': 'net/minecraft/client/gui/GuiPlayerTabOverlay'
            },
            'transformer': function(classNode) {
                print("Transforming ", classNode.name);
            }
        }
    }
}
```
This prints:
```
Initializing Coremod
[...]
Transforming net/minecraft/client/gui/GuiPlayerTabOverlay
```
but then errors out:
```
[CoreMod/XFORM]: Error occurred applying transform of coremod coremod.js function loader
java.lang.ClassCastException: jdk.nashorn.internal.runtime.Undefined cannot be cast to org.objectweb.asm.tree.ClassNode

at net.minecraftforge.coremod.CoreModClassTransformer.transform(CoreModClassTransformer.java:35) 
at net.minecraftforge.coremod.CoreModClassTransformer.transform(CoreModClassTransformer.java:14)
at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:23)

at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:145) 
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:93)
at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:218)

at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:109)
at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:79)

at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 
etc.
```
I also tried adding actual transformer code, but the result is the same.

If it's any relevant, I'm on:
* Forge 25.0.219
* Minecraft 1.13.2
* MCP 20190213.203750
* Java 1.8.0_201
* Linux x64 5.0.9

**Comment by jamierocks** [comment]
I believe the transformer function needs to return the ClassNode.

**Comment by RoccoDev** [comment]
Haha, I totally missed that.
Thank you :)
