### ISSUE TITLE
Some ASM methods are not usable without access to some Java types

### ISSUE THREAD

**Issue by GirafiStudios** [MinecraftForge/CoreMods#26]
Methods like `AbstractInsnNode.clone(Map<LabelNode, LabelNode> clonedLabels)` cannot be called from Nashorn without using `Java.type("java.util.HashMap")` or some other `Map` type, but `CoreModEngine` does not allow access to `java.util.HashMap` (`Java.type("java.util.HashMap")` fails with `java.lang.ClassNotFoundException: java.util.HashMap`).

As far as I can tell, Javascript objects in Nashorn are `Map`s, but only support `String` keys. Doing something like

    var LabelNode = Java.type("org.objectweb.asm.tree.LabelNode");
    var instruction = new LabelNode();
    var map = {};
    instruction.clone(map);

will give an error like:

`key should be a String. It is org.objectweb.asm.tree.LabelNode instead.
java.lang.ClassCastException: key should be a String. It is org.objectweb.asm.tree.LabelNode instead.
    at jdk.nashorn.api.scripting.ScriptObjectMirror.checkKey(ScriptObjectMirror.java:884)
    at jdk.nashorn.api.scripting.ScriptObjectMirror.get(ScriptObjectMirror.java:381)
    at org.objectweb.asm.tree.LabelNode.clone(LabelNode.java:73)
    at jdk.nashorn.internal.scripts.Script$Recompilation$5$18587A$\^eval\_.ASMHelper#cloneInsnList(<eval>:453)
    at jdk.nashorn.internal.scripts.Script$Recompilation$1$909$\^eval\_.initializeCoreMod(<eval>:58)
    at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)`

**Comment by James103** [comment]
As far as I can tell, this is a major problem, preventing several major mods, including [AppleCore](https://github.com/squeek502/AppleCore) and [Iguana Tweaks Reborn](https://www.curseforge.com/minecraft/mc-mods/iguanatweaks-reborn) from being fully ported over to 1.15.

**Comment by Insane96** [comment]
[Iguana Tweaks Reborn](https://www.curseforge.com/minecraft/mc-mods/iguanatweaks-reborn) from being fully ported over to 1.15.

Actually the features required from AppleCore are ports of Hunger Ovehaul.
